language: python
python: "3.9"
install:
  - pip install -e .[ci]
script: make ci

deploy:
  provider: script
  script: bash scripts/deploy.sh
  on:
    branch: master

notifications:
  email:
    recipients:
      - vitaliy.musubi@gmail.com
    on_success: never
    on_failure: always
